/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCreateRouteImport } from './routes/admin/create'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as AdminFormIdRouteImport } from './routes/admin/$formId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCreateRoute = AdminCreateRouteImport.update({
  id: '/admin/create',
  path: '/admin/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFormIdRoute = AdminFormIdRouteImport.update({
  id: '/admin/$formId',
  path: '/admin/$formId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$formId': typeof AdminFormIdRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$formId': typeof AdminFormIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/create': typeof AdminCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/$formId': typeof AdminFormIdRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/create': typeof AdminCreateRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/$formId'
    | '/admin'
    | '/admin/create'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin/$formId' | '/admin' | '/admin/create'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin/$formId'
    | '/admin/_layout'
    | '/admin/create'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminFormIdRoute: typeof AdminFormIdRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminCreateRoute: typeof AdminCreateRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/create': {
      id: '/admin/create'
      path: '/admin/create'
      fullPath: '/admin/create'
      preLoaderRoute: typeof AdminCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/$formId': {
      id: '/admin/$formId'
      path: '/admin/$formId'
      fullPath: '/admin/$formId'
      preLoaderRoute: typeof AdminFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminFormIdRoute: AdminFormIdRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminCreateRoute: AdminCreateRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
